catalog/urls.py
from django.urls import path
from catalog.views import HomeView, ProductDetailView, contacts, BlogCreateView, BlogUpdateView, BlogDeleteView, \
    BlogListView, BlogDetailView, toggle_published, ProductCreateView, ProductUpdateView, ProductDeleteView
from django.conf.urls.static import static
from django.conf import settings
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('contacts/', contacts, name='w'),
    path('blog/', BlogListView.as_view(), name='blg'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create/', BlogCreateView.as_view(), name='create'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='delete'),
    path('blog/<int:pk>/is_published/', toggle_published, name='toggle_published'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from users.apps import UsersConfig
from users.views import UserRegisterView, confirm_email

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', UserRegisterView.as_view(), name='registration'),
    path('confirm_register/<str:token>/', confirm_email, name='confirm_email'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#temlate_name='users/login.html'

catalog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name',]

    def __str__(self):
        '''Добавляем строковое отображение'''
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование', help_text='Укажите наименование товара')
    description = models.TextField(verbose_name='Описание', **NULLABLE, help_text='Опишите товар')
    image = models.ImageField(upload_to='prod_images', verbose_name='Изображение (превью)',
                              **NULLABLE, help_text='Фото товара')
    category = models.ForeignKey('Category', related_name='products', verbose_name='Категория',
                                 on_delete=models.SET_NULL, **NULLABLE, help_text='Категория товара')
    price = models.IntegerField(verbose_name='Цена за покупку', help_text='Стоимость товара')
    created_at = models.DateField(verbose_name='Дата создания (записи в БД)', auto_now_add=True, **NULLABLE)
    updated_at = models.DateField(verbose_name='Дата последнего изменения (записи в БД)', auto_now=True, **NULLABLE)
    from users.models import User
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Пользователь',
                              help_text='Укажите пользователя', **NULLABLE)
    #manufactured_at = models.DateField(verbose_name='Дата производства продукта', auto_now=True, **NULLABLE)
    #view_counter = models.PositiveIntegerField(verbose_name='Счетчик просмотров',
                                               #help_text='Укажите кол-во просмотров', default=0)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['name',]

    def __str__(self):
        '''Добавляем строковое отображение'''
        return f' {self.name}'


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок', help_text='Укажите заголовок')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='Человекопонятный URL', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое', **NULLABLE, help_text='Добавьте описание')
    image = models.ImageField(upload_to='blog_images', verbose_name='Изображение (превью)', **NULLABLE,
                              help_text='Приложите фото')
    created_at = models.DateField(verbose_name='Дата создания', auto_now_add=True, **NULLABLE)
    is_published = models.BooleanField(verbose_name='Опубликовано', default=True)
    view_counter = models.PositiveIntegerField(verbose_name='Счетчик просмотров',
                                               help_text='Укажите кол-во просмотров', default=0)

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'
        ordering = ['created_at', 'is_published', 'view_counter',]

    def __str__(self):
        '''Добавляем строковое отображение'''
        return f'{self.title}'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')

    number = models.FloatField(verbose_name='Номер версии', help_text='Укажите номер версии')
    name = models.CharField(max_length=100, verbose_name='Название версии', **NULLABLE)
    working_ver = models.BooleanField(verbose_name='Признак версии', **NULLABLE,
                                      help_text='Укажите признак текущей версии')

    def __str__(self):
        '''Добавляем строковое отображение'''
        return f'Версия {self.product} == {self.number}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms
from catalog.models import Product, Version


class StyleFormMixin:
    '''Класс стилизации формы'''
    def __init__(self, *args, **kwargs):
        '''Функция стилизации формы'''
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа',
                       'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('created_at', 'updated_at',)

    def clean_name(self):
        '''Функция валидации поля 'name' на недопустимые
        слова из списка forbidden_words.'''
        cleaned_name = self.cleaned_data['name']
        if cleaned_name.lower() in self.forbidden_words:
            raise forms.ValidationError('Ошибка, использовано недопустимое слово в названии!')
        return cleaned_name

    def clean_description(self):
        '''Функция валидации поля 'description'
        на недопустимые слова из списка forbidden_words.'''
        cleaned_data = self.cleaned_data['description']
        if cleaned_data.lower() in self.forbidden_words:
            raise forms.ValidationError('Ошибка, использовано недопустимое слово в описании!')
        return cleaned_data

    # def __init__(self, *args, **kwargs):
    # '''Функция стилизации формы, захештегено,т.к. добавили класс StyleFormMixin'''
    #     super().__init__(*args, **kwargs)
    #     for field_name, field in self.fields.items():
    #         field.widget.attrs['class'] = 'form-control'


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = ('name', 'number',)

catalog/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Blog, Version


# Контроллер CBV
class HomeView(ListView):
    '''Класс вывода всех продуктов.'''
    model = Product
    template_name = 'product_list.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = self.get_queryset()

        for product in products:
            product.versions = Version.objects.filter(product=product)
            product.version = product.versions.filter(working_ver=True).first()

        return context


# Контроллер CBV
class ProductDetailView(DetailView):
    '''Класс вывода детальной информации о продукте.'''
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        versions = Version.objects.filter(product=product)
        context['versions'] = versions
        working_ver = versions.filter(working_ver=True).first()
        context['working_ver'] = working_ver

        return context


class ProductCreateView(CreateView):
    '''Класс создания нов.продукта.'''
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')


class ProductUpdateView(UpdateView):
    '''Класс редактирования данных продукта.'''
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        # Формирование формсета
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        '''Метод валидации.'''
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))


def toggle_working_ver(request, pk):
    '''Функция вывода только рабочих версий'''
    version_item = get_object_or_404(Product, pk=pk)
    if version_item.working_ver:
        version_item.working_ver = False
    else:
        version_item.working_ver = True

    version_item.save()

    return redirect(reverse('catalog:home'))


class ProductDeleteView(DeleteView):
    '''Класс удаления продукта.'''
    model = Product
    success_url = reverse_lazy('catalog:home')


# Контроллер FBV
def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} ({phone}): {message}')
    context = {
        'title': 'contact'
    }
    return render(request, 'catalog/contacts.html', context)


class BlogListView(ListView):
    '''Класс просмотра всех публикаций.'''
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    '''Класс просмотра детальной информации публикации.'''
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_counter += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    '''Класс создания нов.публикации'''
    model = Blog
    fields = ('title', 'content', 'image')
    success_url = reverse_lazy('catalog:blg')


class BlogUpdateView(UpdateView):
    '''Класс редактирования данных публикации'''
    model = Blog
    fields = ('title', 'content', 'image', 'is_published')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self, *args, **kwargs):
        return reverse_lazy('catalog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    '''Класс удаления публикации'''
    model = Blog
    success_url = reverse_lazy('catalog:blg')


def toggle_published(request, pk):
    '''Функция вывода только опубликованных публикаций'''
    publication_item = get_object_or_404(Blog, pk=pk)
    if publication_item.is_published:
        publication_item.is_published = False
    else:
        publication_item.is_published = True

    publication_item.save()

    return redirect(reverse_lazy('catalog:blg'))

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Подтвердите удаление публикации "{{ object.title }}."</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'catalog:blg' %}" class="btn btn-danger">Отменить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top"
                     src="{{ object.image|media_filter }}"
                     alt="Card image cap">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.title }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ object.content|slice:':100' }}</li>
                        <small class="text-body-secondary">Количество просмотров: {{ object.view_counter }}</small>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-secondary">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        {% for blog in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Публикации</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ blog }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    </ul>
                    <li><a href="{% url 'catalog:blog_detail' blog.pk %}" type="button"
                           class="btn btn-lg btn-block btn-outline-secondary">Посмотреть</a></li>
                    <li><a href="{% url 'catalog:update' blog.pk %}" type="button"
                           class="btn btn-lg btn-block btn-outline-secondary">Редактировать</a></li>
                    <li><a href="{% url 'catalog:delete' blog.pk %}" type="button"
                           class="btn btn-lg btn-block btn-outline-secondary">Удалить</a></li>
                </div>
                {% if blog.is_published %}
                <a class="btn btn-warning" href="{% url 'catalog:toggle_published' blog.pk %}">Отменить
                    публикацию</a>
                {% else %}
                <a class="btn btn-success" href="{% url 'catalog:toggle_published' blog.pk %}">Опубликовать</a>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{%endblock%}

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ВКУСВИЛЛ</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">ВКУСВИЛЛ</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-info" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Город</td>
                            <td>Истра</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>7716794420</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Истра, ул.Ленина, дом 65</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-success">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                ВКУСВИЛЛ
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ВКУСВИЛЛ</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{% include 'catalog/includes/inc_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h2 class="display-5">ВКУСВИЛЛ</h2>
    <p class="lead">ВкусВилл — бренд натуральных продуктов с честным и чистым составом.
        Лидеры в доставке продуктов</p>
    <a class="btn btn-info" href="{% url 'catalog:create' %}" role="button">Создать Публикацию</a>
    <a class="btn btn-info" href="{% url 'catalog:product_create' %}" role="button">Создать продукт</a>
</div>
{% block content %}
{% endblock %}
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            ВКУСВИЛЛ
            <small class="d-block mb- text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Подтвердите удаление продукта "{{ object.name }}."</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'catalog:home' %}" class="btn btn-danger">Отменить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top"
                     src="{{ object.image|media_filter }}"
                     alt="Card image cap">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title pricing-card-title">{{ object.price }} руб.</h5>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ object.description|slice:':100' }}</li>
                        <li>Версия: {{ working_ver.name }}</li>
                        <li>Номер: {{ working_ver.number | floatformat }}</li>
                        <li>Признак: {{ working_ver.working_ver }}</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-warning">Купить</button>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

catalog/templates/catalog/product_form.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-secondary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            Версия продукта
                        </div>
                        <div class="card-body">
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{%endblock%}

catalog/templates/catalog/product_info.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top"
                     src="{{ object.image|media_filter }}"
                     alt="Card image cap">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.price }} руб.</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ object.description|slice:':100' }}</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

catalog/templates/catalog/product_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        {% for product in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Описание товара</h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title pricing-card-title">{{ product }}</h5>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    </ul>
                    <li><a href="{% url 'catalog:product_detail' product.pk %}" type="button"
                           class="btn btn-small btn-block btn-outline-secondary">Посмотреть</a></li>
                    <li><a href="{% url 'catalog:product_update' product.pk %}" type="button"
                           class="btn btn-small btn-block btn-outline-secondary">Редактировать</a></li>
                    <li><a href="{% url 'catalog:product_delete' product.pk %}" type="button"
                           class="btn btn-small btn-block btn-outline-secondary">Удалить</a></li>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{%endblock%}